platform :ios, '9.0'

target 'MeditationAppShowcase' do
  use_frameworks!

  pod 'SwiftLint'

  target 'MeditationAppShowcaseTests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.3'

  end

end
